cagenix/users/forms.py
"""cornerstone.users.forms

This file is used to define all the WTForms used by the Users blueprint
"""
from flask_wtf import Form
from wtforms import TextField, validators, HiddenField, PasswordField, BooleanField
from wtforms.ext.sqlalchemy.fields import QuerySelectMultipleField, QuerySelectField
from flask.ext.security import current_user
from cagenix.users.models import Role
from cagenix.practices.models import Practice


strip_filter = lambda x: x.strip() if x else None


class UserCreateForm(Form):
    """This form is used by CS-Admin roles to create new users

    Users require an email and a password. This form uses a QuerySelectField to
    produce a list of Merchants that can optionally be associationed to a user.
    A QuerySelectMulipleField for Roles can also optionally be associated with
    a client. A client can have as many roles as needed.

    :param Form: The WTForms base class
    :type value: object
    :returns: WTForm
    :rtype: object
    """
    email = TextField('Email Address', [validators.Email()], filters=[strip_filter])
    first_name = TextField('First Name', [validators.Length(min=1, max=255)], filters=[strip_filter])
    last_name = TextField('Last Name', [validators.Length(min=1, max=255)], filters=[strip_filter])
    practice = QuerySelectField(get_pk=lambda x: x.id, get_label='practice_name', query_factory=Practice.get_practices, allow_blank=True, blank_text=u'')
    roles = QuerySelectMultipleField(get_label='name', query_factory=Role.get_roles, allow_blank=True, blank_text=u'')


class UserEditForm(Form):
    """This form is used by CS-Admin roles to edit users

    Admins can change the email, active state of the user, associated Merchants,
    and assigned Roles. This form uses a QuerySelectField to produce a list of
    Merchants that can optionally be associationed to a user. A
    QuerySelectMulipleField for Roles can also optionally be associated with
    a client. A client can have as many roles as needed.

    :param Form: The WTForms base class
    :type value: object
    :returns: WTForm
    :rtype: object
    """
    id = HiddenField()
    email = TextField('Email Address', [validators.Email()], filters=[strip_filter])
    #merchant = QuerySelectField(get_pk=lambda x: x.merchant_id, get_label='company_name', query_factory=Merchants.get_merchants, allow_blank=True, blank_text=u'')
    roles = QuerySelectMultipleField(get_label='name', query_factory=Role.get_roles, allow_blank=True, blank_text=u'')
    active = BooleanField('Active')


class UserChangePasswordForm(UserCreateForm):
    """This form is used by CS-Admin roles to change a users password

    This form is used due to the handling of the change password process by
    Flask-Security.

    :param UserCreateForm: The same form used by the Create User process
    :type value: object
    :returns: WTForm
    :rtype: object
    """
    pass


class RoleCreateForm(Form):
    """This form is used by CS-Admin roles to create a new role

    This form is used to create new roles with a name and description.

    :param Form: The WTForms base class
    :type value: object
    :returns: WTForm
    :rtype: object
    """
    name = TextField('Role Name', [validators.Length(min=1, max=255)],
        filters=[strip_filter])
    description = TextField('Description', [validators.Length(min=1, max=255)],
        filters=[strip_filter])


class RoleEditForm(RoleCreateForm):
    """This form is used by CS-Admin roles to edit a role

    This form is used to change the name or description of a role.

    :param RoleCreateForm: The WTForms base class
    :type value: object
    :returns: WTForm
    :rtype: object
    """
    id = HiddenField()

cagenix/users/views.py
"""cagenix.users.views

This file defines the URL routes and controller logic for the users blueprint.
PNT-Admins and App-Admins are the only uses that can access this blueprint.
The Flask-Security roles_accepted decorator is used to require both
authentication and authorization.
"""
import random
import logging
from flask import Blueprint, render_template, redirect, url_for, abort, request
from flask.ext.security import current_user
from flask.ext.security.utils import encrypt_password
from flask.ext.security.decorators import roles_accepted
from flask_mail import Message
from cagenix import db, mail
from cagenix.users.models import User, Role
from cagenix.users.forms import (UserCreateForm, UserEditForm,
    UserChangePasswordForm, RoleCreateForm, RoleEditForm)

log = logging.getLogger(__name__)
mod = Blueprint('users', __name__, url_prefix='/users')


@mod.route('', methods=['GET'])
@roles_accepted('PNT-Admin', 'App-Admin')
def users_home():
    """This function handles the /users endpoint for the blueprint

    It displays a list of users and their roles with the ability to edit or
    change passwords. It also displays a list of roles and descriptions with
    the ability to edit them.  It also offers the ability to add additional
    users and roles.

    :returns: users/index.html
    :rtype: template
    """
    roles = db.session.query(Role).all()
    users_query = db.session.query(User)
    if current_user.has_role('App-Admin'):
        users_query = users_query.filter(-User.roles.name.in_(['PNT-Admin']))
    users = users_query.outerjoin('roles').order_by(Role.name).all()
    return render_template('users/index.html', users=users, roles=roles)


@mod.route('/create', methods=['GET', 'POST'])
@roles_accepted('PNT-Admin', 'App-Admin')
def users_create():
    """This function handles the /users/create endpoint for the blueprint

    It allows PNT-Admins to create users.  It uses the :ref:`users-forms-label`
    to display UsersCreateForm

    :returns: users/index.html
    :rtype: template
    """
    user = User()
    form = UserCreateForm()
    if form.validate_on_submit():
        form.populate_obj(user)
        user.activation_code = ''.join(random.sample('0123456789ABCDEFGHJKMNPQRTVWXYZ', 15))
        msg = Message("Welcome to Cagenix", recipients=[user.email])
        msg.body = "Welcome to the cagenix app, please use the code %(activation_code)s to activate the application" % {'activation_code': user.activation_code}
        mail.send(msg)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.users_home'))
    return render_template('users/create.html', form=form, admin=True)


@mod.route('/edit/<id>', methods=['GET', 'POST'])
@roles_accepted('PNT-Admin', 'App-Admin')
def users_edit(id):
    """This function handles the /users/edit endpoint for the bcornerstone/users/views.py

    It allows PNT-Admins to edit users.  It uses the :ref:`users-forms-label`
    to display UsersEditForm

    :param id: The id of the user being edited
    :type id: int
    :returns: users/edit.html
    :rtype: template
    """
    user = User.by_id(id)
    if not user:
        abort(404)

    form = UserEditForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.users_home'))
    return render_template('users/edit.html', form=form, user_id=user.id, admin=True)


@mod.route('/changepassword/<id>', methods=['GET', 'POST'])
@roles_accepted('PNT-Admin', 'App-Admin')
def users_changepassword(id):
    """This function handles the /users/changepassword endpoint for the blueprint

    It allows PNT-Admins to change a users password.  It uses the
    :ref:`users-forms-label` to display UsersChangePasswordForm

    :param id: The id of the user being edited
    :type id: int
    :returns: users/change_password.html
    :rtype: template
    """
    user = User.by_id(id)
    if not user:
        abort(404)

    form = UserChangePasswordForm(obj=user)
    if form.validate_on_submit():
        form.populate_obj(user)
        user.password = encrypt_password(user.password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.users_home'))
    return render_template('users/change_password.html', form=form, user_id=user.id, admin=True)


@mod.route('/delete/<id>', methods=['GET'])
@roles_accepted('PNT-Admin', 'App-Admin')
def users_delete(id):
    """This function handles the /users/delete endpoint for the blueprint

    It allows PNT-Admins to delete a user.  It is called via a button on
    the ``users/edit.html`` template

    :param id: The id of the user being deleted
    :type id: int
    :returns: users.users_home
    :rtype: redirect
    """
    user = User.by_id(id)
    if not user:
        abort(404)
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('users.users_home'))


@mod.route('/roles/create', methods=['GET', 'POST'])
@roles_accepted('PNT-Admin')
def roles_create():
    """This function handles the /users/roles/create endpoint for the blueprint

    It allows PNT-Admins to create roles.  It uses the :ref:`users-forms-label`
    to display RolesCreateForm

    :returns: users/roles/create.html
    :rtype: template
    """
    role = Role()
    form = RoleCreateForm()
    if form.validate_on_submit():
        form.populate_obj(role)
        db.session.add(role)
        db.session.commit()
        return redirect(url_for('users.users_home'))
    return render_template('users/roles/create.html', form=form, admin=True)


@mod.route('/roles/edit/<id>', methods=['GET', 'POST'])
@roles_accepted('PNT-Admin')
def roles_edit(id):
    """This function handles the /roles/edit endpoint for the blueprint

    It allows PNT-Admins to edit roles.  It uses the :ref:`users-forms-label`
    to display RolesEditForm

    :param id: The id of the role being edited
    :type id: int
    :returns: users/roles/edit.html
    :rtype: template
    """
    role = Role.by_id(id)
    if not role:
        abort(404)

    form = RoleEditForm(obj=role)
    if form.validate_on_submit():
        form.populate_obj(role)
        db.session.add(role)
        db.session.commit()
        return redirect(url_for('users.users_home'))
    return render_template('users/roles/edit.html', form=form, role_id=role.id, admin=True)


@mod.route('/roles/delete/<id>', methods=['GET'])
@roles_accepted('PNT-Admin')
def roles_delete():
    """This function handles the /users/roles/delete endpoint for the blueprint

    It allows PNT-Admins to delete a role.  It is called via a button on the
    ``users/roles/edit.html`` template

    :param id: The id of the role being edited
    :type id: int
    :returns: users.users_home
    :rtype: redirect
    """
    role = Role.by_id(id)
    if not role:
        abort(404)
    db.session.delete(role)
    db.session.commit()
    return redirect(url_for('users.users_home'))

cagenix/templates/users/create.html
{% extends "base.html" %}
{% from "__formhelpers.html" import render_form %}
{% block header %}
<h1 class="page-header">Add New Practitioner</h1>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-8">
    <div class="panel panel-default">
      <div class="panel-heading">
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        {{ render_form(form, action_url=url_for('users.users_create'), action_text='Submit Form') }}
      </div>
      <!-- /.panel-footer -->
    </div>
    <!-- /.panel .chat-panel -->
  </div>
  <!-- /.col-lg-4 -->
</div>
<!-- /.row -->
{% endblock %}

cagenix/templates/users/index.html
{% extends "base.html" %}
{% block header %}
<h1 class="page-header">Practitioners</h1>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-user-md fa-fw"></i> Practitioners
        <div class="pull-right">
          <a href="{{ url_for('users.users_create') }}" class="">Add New</a>
        </div>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Activation Code</th>
                <th>Activated</th>
                <th>Active</th>
                {% if current_user.has_role('PNT-Admin') %}
                <th>Roles</th>
                {% endif %}
                <th>Actions</th>
              </tr>
              <tbody>
              {% for user in users %}
              <tr>
                <td>{{ user.first_name }}</td>
                <td>{{ user.last_name }}</td>
                <td>{{ user.activation_code }}</td>
                <td>{{ user.activated }}</td>
                <td>{{ user.active }}</td>
                {% if current_user.has_role('PNT-Admin') %}
                <th>
                  {% for role in user.roles %}
                    {{ role.name }}&nbsp
                  {% endfor %}
                </th>
                {% endif %}
                <td>
                  <a href="{{ url_for('users.users_edit', id=user.id) }}" class="btn btn-xs btn-warning">Edit</a>
                  <a href="{{ url_for('users.users_delete', id=user.id) }}" class="btn btn-xs btn-danger">Delete</a>
                </td>
              </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- /.panel-footer -->
        </div>
      </div>
      {% if current_user.has_role('PNT-Admin') %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <i class="fa fa-users fa-fw"></i> Roles
          <div class="pull-right">
            <a href="{{ url_for('users.roles_create') }}" class="">Add New</a>
          </div>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Actions</th>
                </tr>
                <tbody>
                {% for role in roles %}
                <tr>
                  <td>{{ role.name }}</td>
                  <td>{{ role.description }}</td>
                  <td>
                    <a href="{{ url_for('users.roles_edit', id=role.id) }}" class="btn btn-xs btn-warning">Edit</a>
                    <a href="{{ url_for('users.roles_delete', id=role.id) }}" class="btn btn-xs btn-danger">Delete</a>
                  </td>
                </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
            <!-- /.panel-footer -->
          </div>
        </div>
        {% endif %}
      </div>
    </div>
    <!-- /.row -->
    {% endblock %}