cagenix/advertisements/models.py
"""cagenix.advertisements.models

This file is used to define all the models used by the Advertisement blueprint
"""

from cagenix import db


class Advertisement(db.Model):
    """The User model defines the authentication users used by Flask-Security

    This Role class defines the model attributes, a classmethod to make finding
    the users easier. It also contains several fields unexposed by the UI. Those
    fields are used to track user logins and access IPs.

    :param db.Model: The SQLAlchemy base database model
    :type db.Model: object
    :param UserMixin: The UserMixin base provided by Flask-Security
    :type UserMixin: object
    """
    __tablename__ = 'cagenix_advertisement'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    asset_location = db.Column(db.String(255))
    position = db.Column(db.String(255))
    active = db.Column(db.Boolean(), default=True)
    counter = db.Column(db.Integer)

    def __repr__(self):
        """__repr__ specifies what a role looks like when viewed in the shell

        :param self: A Role Instance
        :type cls: class
        """
        return '<Ad %r >' % (self.name)

    @classmethod
    def by_id(cls, advertisement_id):
        """by_id returns a User object given a user_id

        :param cls: The calling class
        :type cls: class
        :param advertisement_id: The id of the advertisement being searched for
        :type advertisement_id: int
        """
        return db.session.query(Advertisement).filter(Advertisement.id == advertisement_id).first()

cagenix/advertisements/forms.py
"""cagenix.advertisements.forms

This file is used to define all the WTForms used by the Advertisements blueprint
"""
from flask_wtf import Form
from flask_wtf.file import FileField

from wtforms import TextField, validators, HiddenField, BooleanField


strip_filter = lambda x: x.strip() if x else None


class AdvertisementCreateForm(Form):
    """This form is used by Admin roles to create new Practices

    :param Form: The WTForms base class
    :type value: object
    :returns: WTForm
    :rtype: object
    """
    name = TextField('Ad Name', [validators.Length(min=1, max=255)], filters=[strip_filter])
    position = TextField('Ad Position', [validators.Length(min=1, max=255)], filters=[strip_filter])
    ad_file = FileField('Ad File')


class AdvertisementEditForm(AdvertisementCreateForm):
    """This form is used by Admin roles to edit Advertisements

    :param Form: The WTForms base class
    :type value: object
    :returns: WTForm
    :rtype: object
    """
    id = HiddenField()
    active = BooleanField('Active', [validators.Length(min=1, max=255)], filters=[strip_filter])

cagenix/advertisements/views.py
"""cagenix.advertisements.views

This file defines the URL routes and controller logic for the patients blueprint.
"""

import logging

from flask import Blueprint, render_template, redirect, url_for, abort
from flask import current_app as app
from flask.ext.security.decorators import roles_accepted

from cagenix import db
from cagenix.advertisements.models import Advertisement
from cagenix.advertisements.forms import AdvertisementCreateForm
from cagenix.advertisements.file_handler import s3_upload

log = logging.getLogger(__name__)
mod = Blueprint('advertisements', __name__, url_prefix='/advertisements')


@mod.route('', methods=['GET'])
@roles_accepted('PNT-Admin', 'App-Admin')
def home():
    """This function handles the /users endpoint for the blueprint

    It displays a list of users and their roles with the ability to edit or
    change passwords. It also displays a list of roles and descriptions with
    the ability to edit them.  It also offers the ability to add additional
    users and roles.

    :returns: users/index.html
    :rtype: template
    """
    ads = db.session.query(Advertisement).all()
    advertisements = []
    for ad in ads:
        advertisements.append(
            {
                'name': ad.name,
                'position': ad.position,
                'active': ad.active,
                'asset_location': app.config['AWS_LOCATION'] + app.config['AWS_DIRECTORY'] + '/' + ad.asset_location,
                'ad_id': ad.id,
            }
        )

    return render_template('advertisements/index.html', advertisements=advertisements)


@mod.route('/create', methods=['GET', 'POST'])
@roles_accepted('PNT-Admin', 'App-Admin')
def advertisements_create():
    """This function handles the /users/create endpoint for the blueprint

    It allows PNT-Admins to create users.  It uses the :ref:`users-forms-label`
    to display UsersCreateForm

    :returns: users/index.html
    :rtype: template
    """
    ad = Advertisement()
    form = AdvertisementCreateForm()
    if form.validate_on_submit():
        form.populate_obj(ad)
        ad.asset_location = s3_upload(form.ad_file)
        db.session.add(ad)
        db.session.commit()
        return redirect(url_for('advertisements.home'))
    return render_template('advertisements/create.html', form=form, admin=True)


@mod.route('/delete/<ad_id>', methods=['GET'])
@roles_accepted('PNT-Admin', 'App-Admin')
def advertisements_delete(ad_id):
    """This function handles the /users/create endpoint for the blueprint

    It allows PNT-Admins to create users.  It uses the :ref:`users-forms-label`
    to display UsersCreateForm

    :returns: users/index.html
    :rtype: template
    """
    ad = Advertisement.by_id(ad_id)
    db.session.delete(ad)
    db.session.commit()

    return redirect(url_for('advertisements.home'))

cagenix/templates/advertisements/create.html
{% extends "base.html" %}
{% from "__formhelpers.html" import render_form %}
{% block header %}
<h1 class="page-header">Add New Advertisement</h1>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-8">
    <div class="panel panel-default">
      <div class="panel-heading">
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        {{ render_form(form, action_url=url_for('advertisements.advertisements_create'), action_text='Submit Form') }}
      </div>
      <!-- /.panel-footer -->
    </div>
    <!-- /.panel .chat-panel -->
  </div>
  <!-- /.col-lg-4 -->
</div>
<!-- /.row -->
{% endblock %}

cagenix/templates/advertisements/index.html
{% extends "base.html" %}
{% block header %}
<h1 class="page-header">Advertisements</h1>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <i class="fa fa-user-md fa-fw"></i> Advertisements
        <div class="pull-right">
          <a href="{{ url_for('advertisements.advertisements_create') }}" class="">Add New</a>
        </div>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Active</th>
                <th>Image</th>
                <th>Actions</th>
              </tr>
              <tbody>
              {% for ad in advertisements %}
              <tr>
                <td>{{ ad.name }}</td>
                <td>{{ ad.position }}</td>
                <td>{{ ad.active }}</td>
                <td><img src="{{ ad.asset_location }}" height="150px"></img></td>
                <td><a href="{{ url_for('advertisements.advertisements_delete', ad_id=ad.ad_id) }}" class="btn btn-xs btn-danger">Delete</a></td>
              </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- /.panel-footer -->
        </div>
      </div>
    </div>
  </div>
<!-- /.row -->
{% endblock %}