cagenix/practices/models.py
"""cagenix.practices.models

This file is used to define all the models used by the Practices blueprint
"""

from cagenix import db


class Practice(db.Model):
    """The Practice model defines the authentication users used by Flask-Security

    :param db.Model: The SQLAlchemy base database model
    :type db.Model: object
    """
    __tablename__ = 'cagenix_practice'
    id = db.Column(db.Integer, primary_key=True)
    practice_name = db.Column(db.String(255))
    address_one = db.Column(db.String(255))
    address_two = db.Column(db.String(255))
    city = db.Column(db.String(255))
    state = db.Column(db.String(255))
    zip_code = db.Column(db.String(10))
    url = db.Column(db.String(255))
    primary_color = db.Column(db.String(255))
    secondary_color = db.Column(db.String(255))
    phone = db.Column(db.String(12))
    active = db.Column(db.Boolean())
    practioneers = db.relationship('User', backref='practice', lazy='dynamic')
    patients = db.relationship('Patient', backref='practice', lazy='dynamic')

    def __repr__(self):
        """__repr__ specifies what a role looks like when viewed in the shell

        :param self: A Practice Instance
        :type cls: class
        """
        return '<practice %r>' % (self.practice_name)

    @classmethod
    def by_id(cls, practice_id):
        """by_id returns a User object given a user_id

        :param cls: The calling class
        :type cls: class
        :param user_id: The id of the user being searched for
        :type user_id: int
        """
        return db.session.query(Practice).filter(Practice.id == practice_id).first()

    @classmethod
    def by_phone(cls, phone):
        """by_phone returns a User object given a phone number

        :param cls: The calling class
        :type cls: class
        :param phone: The phone number of the user being searched for
        :type phone: string
        """

    @classmethod
    def get_practices(cls):
        """get_practices returns a list of Practice objects

        :param cls: The calling class
        :type cls: class
        """
        return db.session.query(Practice).order_by(Practice.practice_name)

cagenix/practices/forms.py
"""cagenix.practices.forms

This file is used to define all the WTForms used by the Practices blueprint
"""
from flask_wtf import Form
from wtforms import TextField, validators, HiddenField, BooleanField


strip_filter = lambda x: x.strip() if x else None


class PracticeCreateForm(Form):
    """This form is used by Admin roles to create new Practices

    :param Form: The WTForms base class
    :type value: object
    :returns: WTForm
    :rtype: object
    """
    practice_name = TextField('Practice Name', [validators.Length(min=1, max=255)], filters=[strip_filter])
    address_one = TextField('Address One', [validators.Length(min=1, max=255)], filters=[strip_filter])
    address_two = TextField('Address Two', [], filters=[strip_filter])
    city = TextField('City', [validators.Length(min=1, max=255)], filters=[strip_filter])
    state = TextField('State', [validators.Length(min=1, max=255)], filters=[strip_filter])
    zip_code = TextField('ZIP Code', [validators.Length(min=1, max=255)], filters=[strip_filter])
    url = TextField('Website Address', [validators.Length(min=1, max=255)], filters=[strip_filter])
    phone = TextField('Phone Number', [validators.Length(min=1, max=255)], filters=[strip_filter])


class PracticeEditForm(PracticeCreateForm):
    """This form is used by Admin roles to edit Practices

    :param Form: The WTForms base class
    :type value: object
    :returns: WTForm
    :rtype: object
    """
    id = HiddenField()
    active = BooleanField('Active', [validators.Length(min=1, max=255)], filters=[strip_filter])

cagenix/practices/views.py
"""cagenix.patients.views

This file defines the URL routes and controller logic for the patients blueprint.
"""

import logging
from flask import Blueprint, render_template, redirect, url_for

from flask.ext.security.decorators import roles_accepted
from cagenix import db

from .models import Practice
from .forms import PracticeCreateForm

log = logging.getLogger(__name__)
mod = Blueprint('practices', __name__, url_prefix='/practices')


@mod.route('', methods=['GET'])
@roles_accepted('PNT-Admin', 'App-Admin')
def home():
    practices = Practice.query.all()
    return render_template('practices/index.html', practices=practices)


@mod.route('/create', methods=['GET', 'POST'])
@roles_accepted('PNT-Admin', 'App-Admin')
def practices_create():
    """This function handles the /practices/create endpoint for the blueprint

    It allows Admins to create Practices.  It uses the :ref:`practices-forms-label`
    to display PracticesCreateForm

    :returns: practices/create.html
    :rtype: template
    """
    practice = Practice()
    form = PracticeCreateForm()
    if form.validate_on_submit():

        form.populate_obj(practice)
        db.session.add(practice)
        db.session.commit()
        return redirect(url_for('practices.home'))
    return render_template('practices/create.html', form=form)


@mod.route('/delete/<practice_id>', methods=['GET'])
@roles_accepted('PNT-Admin', 'App-Admin')
def practices_delete(practice_id):
    """This function handles the /users/create endpoint for the blueprint

    It allows PNT-Admins to create users.  It uses the :ref:`users-forms-label`
    to display UsersCreateForm

    :returns: users/index.html
    :rtype: template
    """
    practice = Practice.by_id(practice_id)
    db.session.delete(practice)
    db.session.commit()

    return redirect(url_for('practices.home'))

cagenix/templates/practices/create.html
{% extends "base.html" %}
{% from "__formhelpers.html" import render_form %}
{% block header %}
<h1 class="page-header">Add New Practice</h1>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-8">
    <div class="panel panel-default">
      <div class="panel-heading">
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        {{ render_form(form, action_url=url_for('practices.practices_create'), action_text='Submit Form') }}
      </div>
      <!-- /.panel-footer -->
    </div>
    <!-- /.panel .chat-panel -->
  </div>
  <!-- /.col-lg-4 -->
</div>
<!-- /.row -->
{% endblock %}

cagenix/templates/practices/index.html
{% extends "base.html" %}
{% block header %}
<h1 class="page-header">Practices</h1>
{% endblock %}
{% block content %}
<div class="row">
  <div class="col-lg-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <a href="{{ url_for('practices.practices_create') }}" class="">Add New</a>
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
              <tr>
                <th>Name</th>
                <th>City</th>
                <th>State</th>
                <th>Practioners</th>
                <th>Actions</th>
              </tr>
              <tbody>
              {% for practice in practices %}
              <tr>
                <td>{{ practice.practice_name }}</td>
                <td>{{ practice.city }}</td>
                <td>{{ practice.state }}</td>
                <td>{{ practice.practioneers.count() }}</td>
                <td><a href="{{ url_for('practices.practices_delete', practice_id=practice.id) }}" class="btn btn-xs btn-danger">Delete</a></td>
              </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <!-- /.panel-footer -->
        </div>
        <!-- /.panel .chat-panel -->
      </div>
      <!-- /.col-lg-4 -->
    </div>
    <!-- /.row -->
    {% endblock %}